---
server:
  port: 12345
spring:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driverClassName: ${spring.datasource.driverClassName}
  jpa:
    show-sql: ${spring.jpa.show-sql}
    hibernate:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}