---
server:
  port: 51849
application:
  version: 1.0-SNAPSHOT
  formatted-version: v01.00.000-SNAPSHOT
  title: Animal Battle Server
Ansi:
  NAME: Animal Battle
spring:
  output:
    ansi:
      enabled: always
---
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:warGameAngularjsServer;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
---
spring:
  profiles: sql
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=wargameangularserver;instance=SQLEXPRESS
    username: sa
    password: n0ne@H0me
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop